### ISSUE TITLE
Can't fetch embed_mat.npy

### ISSUE THREAD

**Issue by DuinoDu** [nusnlp/amanda#2]
"https://tinyurl.com/ybdvpxcr/searchqa/embed_mat.npy" is not reached for me when running [this line](https://github.com/nusnlp/amanda/blob/master/SEARCHQA/src/run_dataprep.sh#L54). But it seems that `embed_mat.npy` can be generated by `prep-data/prep_embed_mat.py`, while [it](https://github.com/nusnlp/amanda/blob/master/SEARCHQA/src/run_dataprep.sh#L59) is commented and there is no `prep-data/prep_embed_mat.py`. 
Would you mind providing `prep_embed_mat.py`?
Much thanks~

**Comment by sk210892** [comment]
I checked the download link and it seems fine to me. What is the issue you are facing?

**Comment by DuinoDu** [comment]
I tried 10 minutes ago and I can download it now.
Thanks.
