### ISSUE TITLE
not able to run searchqa test

### ISSUE THREAD

**Issue by mujtabahasan** [nusnlp/amanda#3]
Hi,
I am trying to run SEARCHQA after downloading your trained model. I am getting an error, though. Traceback is below:
../amanda/model.py:140: UserWarning: The `merge` function is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.
  joint_enc = merge([joint_enc2, joint_enc], mode='mul')
Traceback (most recent call last):
  File "src/test_searchqa.py", line 255, in <module>
    model = G.create_model_graph()
  File "../amanda/model.py", line 146, in create_model_graph
    self.h))(encoding_pre)
  File "../amanda/my_layers.py", line 32, in __init__
    self.init = initializations.get(init)
NameError: global name 'initializations' is not defined

The file my_layers.py has no other reference of initializations. Also, what version of theano is needed

**Comment by sk210892** [comment]
Try with keras-1.1.0, theano-0.9.0, cudnn-v5

**Comment by mujtabahasan** [comment]
Thanks, it worked..

Had to add a line `from keras import initializations` to my_layers.py though
