### ISSUE TITLE
which version of keras and theano ?

### ISSUE THREAD

**Issue by charles0-0** [nusnlp/amanda#4]
I have tried the couple of keras 1.2.2(2.0.0/2.1.0) and theano 0.9(1.0.1),  all went wrong!?  and the errors come from package of keras or theano .

**Comment by sk210892** [comment]
Try with keras-1.1.0, theano-0.9

**Comment by charles0-0** [comment]
thanks, it works.  I wonder how long will it takes for the training?  (use MacBook Pro2017  I7+16G, without nvida )

**Comment by sk210892** [comment]
I have never trained with CPU
