### ISSUE TITLE
Version of all the Software Requirements

### ISSUE THREAD

**Issue by pabitralenka** [nusnlp/amanda#5]
Hi @sk210892. Can you please specify the exact versions of all the packages you have used for various software requirements for NEWSQA. I am having a lot of compatibility issues to run the code for NEWSQA. It would also be great if you can verify that whether the code in this repo works fine with NewsQA data.

Thank you

**Comment by sk210892** [comment]
Keras-1.1.0, theano-0.9, cudnn-v5
