### ISSUE TITLE
Error in running the code with NEWSQA 

### ISSUE THREAD

**Issue by pabitralenka** [nusnlp/amanda#6]
Hi @sk210892. For NEWSQA, I have followed all the necessary steps till tokenization of train, dev and test data. During the tokenization step, there were some token mismatch in all of train, dev and test data. Then for the indexing of the data (here train data) using this command
`python prep-data/data_prep_with_char.py -data=data/tokenized-train-v1.1.json -id2w=prep-data/id2word.json -id2c=prep-data/id2char.json -wr=data/train_indexed.json`

I am getting this error 
`
Traceback (most recent call last):
  File "prep-data/data_prep_with_char.py", line 135, in <module>
    cqa = newsqa.prep_data()
  File "prep-data/data_prep_with_char.py", line 104, in prep_data
    label_start[qa['answers'][0]['answer_start']] = 1
TypeError: list indices must be integers, not unicode
`

Similarly, this error is repeated for dev and test as well. So for this, I tried to change some code in `data_prep_with_char.py`. You can view the changed code [here](https://codeshare.io/aYnLpL) (Line: 97).

Please let me know if the changes I have made are valid or not.

**Comment by sk210892** [comment]
You should not get token mismatch for all the samples in train, dev and test. We used nltk-3.2.1 for tokenization.

**Comment by pabitralenka** [comment]
@sk210892 Thanks. I will try it and let you know. Can you please mention what are the versions of numpy and pandas you have used?

**Comment by sk210892** [comment]
numpy-1.13.3
pandas-0.18.1

**Comment by pabitralenka** [comment]
@sk210892 After updating to all of your instructions, I still keep on getting token mismatch (about 40-45) in train, dev, and test samples combined. And the error is specific to NewsQA data only. However, SearchQA data works fine without any token mismatch.

One such instance of a token mismatch

[error 0] token mismatch answer
context **[u'to', u'learn', u'how', u'to', u'side', u'step', u'security', u'measures', u'or', u'create', u'their', u'own', u'``', u'botnet', u'referring', u'to']**

answer **[u'kits', u'to', u'learn', u'how', u'to', u'side', u'step', u'security', u'measures', u'or', u'create', u'their', u'own', u'``', u'botnet', u'r']
count  1**

Can you please help me out with this?

**Comment by sk210892** [comment]
That amount of token mismatch is fine in NewsQA. It is expected.

**Comment by pabitralenka** [comment]
@sk210892 After tokenization, in the indexing of train, test, and dev data, I still get this error 
`Traceback (most recent call last): File "prep-data/data_prep_with_char.py", line 135, in <module> cqa = newsqa.prep_data()` 
`File "prep-data/data_prep_with_char.py", line 104, in prep_data label_start[qa['answers'][0]['answer_start']] = 1` 
`TypeError: list indices must be integers, not unicode`

Can you please help me to fix this error?

**Comment by sk210892** [comment]
Can you try now? Use the modified code.

**Comment by pabitralenka** [comment]
@sk210892 Thank you very much. This worked. 

I had modified one of `['answers']` to `['answer]'` in my first comment in this issue (in which I had shared the code too). But I missed another `['answers']` to modify.
