### ISSUE TITLE
test_newsqa predict_batch_size affects results

### ISSUE THREAD

**Issue by Jmallins** [nusnlp/amanda#9]
When changing the batch size at test time  (test_newsqa) using -pbs . I get different results. F1 ranges from 0.6265. to 0.57. with batch sizes varying from 1 to 16.  Is this to be expected?

**Comment by sk210892** [comment]
Results might differ with batch sizes because of the padding. We could only test with batch size 4 due to memory constraint.

**Comment by Jmallins** [comment]
Shouldn't padding be ignored? is this not a bug then?
